// This file was automatically generated by a python scipt which uses a csv file for the source.
#pragma once

#include "configuration.h"

namespace configuration {
const setting defaultSettings[]{
	setting{"Dark_Theme", SettingType::Boolean, true},
	setting{"Scripts_Folder", SettingType::String, "../"},
};
}
