f = open("default_settings.csv", "r")
header = open("default_settings.h", "w")

header.write("// This file was automatically generated by a python scipt which uses a csv file for the source.\n")

header.write("#pragma once\n\n")
header.write("#include \"configuration.h\"\n\n")
header.write("namespace configuration {\n")
header.write("const setting defaultSettings[]{\n")

types = {
	"b" : "SettingType::Boolean",
	"i" : "SettingType::Integer",
	"f" : "SettingType::Float",
	"s" : "SettingType::String",
	"c" : "SettingType::Letter"
}

# Skip first entry.
f = [line[:-1] for line in f]
rows = iter(f)
next(rows)

for row in rows:
	print(row)
	col = row.split(",")
	header.write("	setting{{\"{0}\", {1}, {2}}},\n".format(col[0],types[str(col[1])], col[2]))

header.write("};\n")
header.write("}\n")
